# User
# Write a one-line Python generator or iterator expression that returns the infinite sequence of increasing integers generated by repeatedly adding the ascii values of each letter in the word “Close” to itself. 67, 175, 286, 401, 502, 569, 677, 788, 903 is the beginning of this sequence. Assume any needed Python standard library modules are already imported
import itertools

generator_expression = (sum(ord(c) for c in 'Close') + n * sum(ord(c) for c in 'Close') for n in itertools.count())

sequence = [next(generator_expression) for _ in range(10)]

print(sequence)